### ISSUE TITLE
LESS formatting - variable interpolation 

### ISSUE THREAD

**Issue by retan** [beautify-web/js-beautify#1017]
# Description

LESS files are not aligned properly if variable interpolation is used.
# Input

``` less
.class-@{name} {
    display: block;
}
```
# Expected Output

The beautified code should look the same as the input.
# Actual Output

``` less
.class-@ {
    name
}

{
    display: block;
}
```
### Environment

Windows 10
### Related

Previously reported in: https://github.com/brackets-beautify/brackets-beautify/issues/222
