### ISSUE TITLE
LESS formatting - mixins with multiple variables

### ISSUE THREAD

**Issue by retan** [beautify-web/js-beautify#1018]
# Description

LESS files are not aligned properly if a mixin has multiple semicolon separated parameters. Semicolons (as opposed to commas, which can be use for this purpose as well) are the preferred for separating parameters. See: http://lesscss.org/features/#mixins-parametric-feature-mixins-with-multiple-parameters
# Input

``` less
.mymixin(@color: #ccc; @border-width: 1px)  {
    border: @border-width solid @color;
}
```
# Expected Output

The beautified code should look the same as the input above.
# Actual Output

``` less
.mymixin(@color: #ccc;
@border-width: 1px) {
    border: @border-width solid @color;
}
```
### Environment

Windows 10
### Related

Previously reported in: https://github.com/brackets-beautify/brackets-beautify/issues/222
