### ISSUE TITLE
CSS Single line formatting

### ISSUE THREAD

**Issue by Alex360hd** [beautify-web/js-beautify#1124]
Hello,

I didn't see any option to format CSS in a single line way :

Old output :

    .btn-primary {
      background:#fff;
      color:#000;
      border:1px solid #000;
    }
    .btn-primary:hover {
      background:#000;
      color:#fff;
      border:1px solid #fff;
    }

Desired output :

    .btn-primary { background:#fff; color:#000; border:1px solid #000; }
    .btn-primary:hover { background:#000; color:#fff; border:1px solid #fff; }

For me (and many developpers), it's far easier to read and to work on css formatted that way.

**Comment by bitwiseman** [comment]
Duplicate of #330. But given the age of that request, I'm keeping this one open.

**Comment by jsonchou** [comment]
visual studio has a compact feature for *.css files, just like @Alex360hd  wished.
visual studio code with extention-plugins from js-beauty has not this feature yet.
compact feature makes your code 1000 rows(compact) vs 5000 rows(old formatting),  you can control your *.css file with God Perspective.
from sass/less long code hater.

**Comment by Zmove** [comment]
Yep, +1 for that. I really like css single line formatting, each selector are next to each other and it give a very good perspective view.

**Comment by olets** [comment]
I would expect to use a minifier to turn multi-line styles into single-line, and a beautifier to turn single-line into multi-line.

Following up on @evocateur's #330 [opinion](330#issuecomment-26067389): the `cssmin` mentioned there has been deprecated in favor of [`clean-css`](/jakubpawlowicz/clean-css) (see also [How to use clean-css with build tools?](/jakubpawlowicz/clean-css#how-to-use-clean-css-with-build-tools)). "Single line formatting" is easy to get with `clean-css` - the simplest settings are

```js
level: 0, // no optimizations
format: {
    breaks: {
        afterRuleEnds: true // put a line break after every rule
    }
}
```

**Comment by jsonchou** [comment]
every young developer of my colleagues write every single line with long long long less/sass, and complie everywhere.

forgive my pool code -_-!!.

```javascript
let CSSIOStream=`.model-a {
  background:#fff;
  color:  #aaa;
  border:  1px solid #aaa;
  border-radius  : 5px;
}
.model-a:hover {
  background:#000;
  color:#fff;
  border:1px solid #fff;
}

/*seperate page section style, normally, i will left one blank rows or a note*/

.model-b{margin-right:10px;}
.model-b-list{margin-right:10px;}

/*seperate page section style, normally, i will left one blank rows or a note*/



`;


let CSSIOStreamOutput=CSSIOStream
.replace(/\ +/g, ' ')
.replace(/;\n/g,';')
.replace(/{\n/g,'{')

console.log(CSSIOStreamOutput);
```

output:
```css
.model-a { background:#fff; color: #aaa; border: 1px solid #aaa; border-radius : 5px;}
.model-a:hover { background:#000; color:#fff; border:1px solid #fff;}

/*seperate page section style, normally, i will left one blank rows or a note*/

.model-b{margin-right:10px;}
.model-b-list{margin-right:10px;}

/*seperate page section style, normally, i will left one blank rows or a note*/




```


just compact the code between{}, .scss&.less file is excluded.
