### ISSUE TITLE
Add brace_style option for CSS

### ISSUE THREAD

**Issue by Hirse** [beautify-web/js-beautify#1259]
# Description
Based on this Stackoverflow [question](https://stackoverflow.com/q/45708124/1469028) and [answer](https://stackoverflow.com/a/46304248/1469028) there seems to be a desire to configure the brace style for CSS in order to have opening braces on a new line.

# Input
The code looked like this before beautification:
```css
#icon {
    background-color: blue;
}
```

# Expected Output
The code should have looked like this after beautification:
```css
#icon
{
    background-color: blue;
}
```

# Actual Output
The  code actually looked like this after beautification:
```css
#icon {
    background-color: blue;
}
```

## Settings
```json
{
    "brace_style": "expand"
}
```
