### ISSUE TITLE
Keep single-row rules in CSS?

### ISSUE THREAD

**Issue by Gennady-G** [beautify-web/js-beautify#1299]
# Description
Greetings!

if I have this 
`footer {  padding: 1%;  }`

then after Shift+Alt+F I get 
```
    footer {
        padding: 1%;
    }
```
Is there an option to kee 'one-line-rule' as it is?

Tried 
`"beautify.options": {"brace_style": "collapse,preserve-inline"}`
but no luck

## Settings
Example:
```json
 {
    "window.zoomLevel": -1,
    "workbench.sideBar.location": "right",
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "editor.cursorStyle": "underline",
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.donotVerifyTags": false,
    "html.format.contentUnformatted": "pre,code,textarea,li",  
}
```

**Comment by bitwiseman** [comment]
This is related to #1124, but separate since it is asking only to preserve  one-line rules.
Neither are present at this time.

**Comment by Gennady-G** [comment]
Thank You for response @bitwiseman ! :)

**Comment by kleber-swf** [comment]
Maybe it should be an option like `max_preserve_single_line_properties` configured with the maximum number of properties to keep in a single line.

Formatted:
```css
.fill {
	flex: 1 1 auto;
}

.item-name input {
	font-size: 1.5em;
}

.avatar {
	border-radius: 50%;
	margin-right: 10px
}

.avatar-32 {
	width: 32px;
	height: 32px
}

.avatar-64 {
	width: 64px;
	height: 64px
}

.avatar-100 {
	width: 100px;
	height: 100px
}

.avatar-128 {
	width: 128px;
	height: 128px
}

.details {
	padding: 2em;
}

.form-actions {
	direction: rtl;
}
```

Desired result:
```css
.fill { flex: 1 1 auto; }
.item-name input { font-size: 1.5em; }

.avatar { border-radius: 50%; margin-right: 10px }
.avatar-32 { width: 32px; height: 32px }
.avatar-64 { width: 64px; height: 64px }
.avatar-100 { width: 100px; height: 100px }
.avatar-128 { width: 128px; height: 128px }

.details { padding: 2em; }
.form-actions { direction: rtl; }
```
