### ISSUE TITLE
Website "autodetect" setting doesn't distinguish css vs javascript

### ISSUE THREAD

**Issue by Hirse** [beautify-web/js-beautify#1565]
# Description
When formatting CSS with a `url()` attribute value, a space is inserted after the protocol of an unquoted URL value.

Reported as https://github.com/brackets-beautify/brackets-beautify/issues/270.

# Input
The code looked like this before beautification:
```css
class{ background: url(http://someurl/img.png) }
```

# Expected Output
The code should have looked like this after beautification:
```css
.class {
  background: url(http://someurl/img.png) }
```

# Actual Output
The  code actually looked like this after beautification:
```css
.class {
  background: url(http: //someurl/img.png) }
                       ^
               space inserted here
```

# Steps to Reproduce
Reproducable on https://beautifier.io/ with default settings.

**Comment by bitwiseman** [comment]
@Hirse 
Are you sure?  On   https://beautifier.io/ w v1.8.6 in `CSS` mode, I get this output:
```css
.class {
  background: url(http://someurl/img.png)
}
```
