### ISSUE TITLE
CSS "space_around_combinator" not working

### ISSUE THREAD

**Issue by prettydiff** [beautify-web/js-beautify#1638]
# Description
An issue with CSS selector spacing

https://github.com/Glavin001/atom-beautify/issues/2291

# Input
The code looked like this before beautification:
```css
.container>a {
  position: relative;
}
```

# Expected Output
The code should have looked like this after beautification:
```css
.container > a {
  position: relative;
}
```

# Actual Output
The  code actually looked like this after beautification:
```css
.container>a {
  position: relative;
}
```
