### ISSUE TITLE
Beautifier wrap inline comments near css rules

### ISSUE THREAD

**Issue by Unknow-max** [beautify-web/js-beautify#1773]
# Beautifier wrap inline comments near css rules

## Input
The code looked like this before beautification:

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, .4),
      rgba(0, 0, 0, .6)), url("../../images/backgrounds/team.png") center/cover; /* 1 */
  height: .1rem; /* 2 */
  min-height: 100vh;
}
```

## Expected Output
The code should have looked like this after beautification (same):

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, .4),
      rgba(0, 0, 0, .6)), url("../../images/backgrounds/team.png") center/cover; /* 1 */
  height: .1rem; /* 2 */
  min-height: 100vh;
}
```

## Actual Output
The  code actually looked like this after beautification, you can note that beautify wrap the inline comments, and obviously I don't want this ugly behavior.

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.6)), url("../../images/backgrounds/team.png") center/cover;
  /* 1 */
  height: .1rem;
  /* 2 */
  min-height: 100vh;
}
```
---

## Steps to Reproduce
Simply copy the css code, and try to run beautify **no configuration is needed**

## Environment
OS: Windows 10 Home 6/03/2020 18363.720

---
## Settings

```json
{
   "indent_size": 2, 
"end_with_new_line": true
}
```
*Please note: This behavior is independent from the configuration file, you can notice with any configuration*.
