### ISSUE TITLE
Escape Mustache / Handlebar delimiters when beautifying css

### ISSUE THREAD

**Issue by Hyperblaster** [beautify-web/js-beautify#1775]
Currently using the beautifier to pretty up the following css

```scss
.box {
    display: flex;
    color: {{data.color}};
}
```
On Beautification it turns into this
```scss
.box {
    display: flex;
    color: {
            {
            data.color
        }
    }
}
```

I'm pretty sure that the 'unformatted_content_delimiter' option is what is needed to allow for {{token}} to be escaped from beautification, but i can't find in the documentation how to specify it nor any examples.
