### ISSUE TITLE
CSS formatter inserts unexpected spaces in attribute selector and breaks the syntax

### ISSUE THREAD

**Issue by ntnyq** [beautify-web/js-beautify#2052]
# Description

## Input
The code looked like this before beautification:
```
.foo[class~="bar"] {
    color: red;
}

.foo[class*="bar"] {
    color: red;
}

.foo+.foo {
    color: red;
}
```

## Current Output
The  code actually looked like this after beautification:
```
.foo[class ~ ="bar"] {
    color: red;
}

.foo[class*="bar"] {
    color: red;
}

.foo + .foo {
    color: red;
}
```

## Expected Output
The code should have looked like this after beautification:
```
.foo[class~="bar"] {
    color: red;
}

.foo[class*="bar"] {
    color: red;
}

.foo + .foo {
    color: red;
}
```

# Environment

## Browser User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

Language Selected:
Beautify CSS

## Settings
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false,
  "space_around_selector_separator": true
}
```

**Comment by xuld** [comment]
Input: 
```scss
.x {
       $d: a !default;
	@if $x != 0 {
		color: $var !important;
	}
}
```

Actual Output:
```scss
.x {
       $d: a  !default;   // BUG !
	@if $x  !=0 {   // BUG !!
		color: $var  !important;    // BUG !!!
	}
}
```
