### ISSUE TITLE
Extra space before `!important` added

### ISSUE THREAD

**Issue by aeschli** [beautify-web/js-beautify#2056]
Input: 
```scss
.x {
       $d: a !default;
	@if $x != 0 {
		color: $var !important;
	}
}
```

Actual Output:
```scss
.x {
       $d: a  !default;   // BUG !
	@if $x  !=0 {   // BUG !!
		color: $var  !important;    // BUG !!!
	}
}
```

_Originally posted by @xuld in https://github.com/beautify-web/js-beautify/issues/2052#issuecomment-1120171915_
Also reported by https://github.com/microsoft/vscode/issues/150318
