### ISSUE TITLE
CSS Grid shorthand newlines not preserved

### ISSUE THREAD

**Issue by Myned** [beautify-web/js-beautify#2214]
# Description
The [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) shorthand property does not preserve newlines when formatted.

Likely the same issue as https://github.com/beautify-web/js-beautify/issues/1817, but PR https://github.com/beautify-web/js-beautify/pull/2018 does not seem to take into account the implicit shorthand.

# Input
The code looked like this before beautification:
```css
grid:
    "header" auto
    "main" 1fr
    "footer" auto;
```

# Expected Output
The code should have looked like this after beautification:
```css
grid:
    "header" auto
    "main" 1fr
    "footer" auto;
```

# Actual Output
The  code actually looked like this after beautification:
```css
grid:
    "header" auto "main" 1fr "footer" auto;
```

# Steps to Reproduce
1. Format the below with [beautifier.io](https://beautifier.io)
```css
body {
    grid:
        "test test test" 1fr
        ".    .    ." 1fr
        / 1fr 1fr;
    
    grid-template:
        "test test test" 1fr
        ".    .    ." 1fr
        / 1fr 1fr;
}
```
2. Observe formatted `grid` and untouched `grid-template`
```css
body {
    grid:
        "test test test" 1fr ".    .    ." 1fr / 1fr 1fr;
    
    grid-template:
        "test test test" 1fr
        ".    .    ." 1fr
        / 1fr 1fr;
}
```

## Environment
OS: Arch Linux GNOME Wayland 45.1, Kernel 6.5.9
Application: Beautifier.io and Visual Studio Code

## Settings
Beautifier.io defaults
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```
