### ISSUE TITLE
Add or preserve empty line between CSS rules

### ISSUE THREAD

**Issue by drewhamlett** [beautify-web/js-beautify#467]
Forgive me if this has been asked before but is there a way to keep spacing between CSS rules when formatting?

```css
.login {
    margin-top: 30px;
    padding: 30px;
    background: rgba(255, 255, 255, 0.7);
}

.login.btn {
    border-radius: 0;
    background-color: #5C6166;
    border-color: #4a4a4a;
}
```

To:

```css
.login {
    margin-top: 30px;
    padding: 30px;
    background: rgba(255, 255, 255, 0.7);
}
.login.btn {
    border-radius: 0;
    background-color: #5C6166;
    border-color: #4a4a4a;
}
```
