### ISSUE TITLE
beautify css with media query

### ISSUE THREAD

**Issue by michalliu** [beautify-web/js-beautify#480]
The following code

``` css
@media only screen and (min-width:1000px){body{width:760px;margin:0 auto}}
```

will produce

``` css
@media only screen and(min-width:1000px) {
    body {
        width:760px;
        margin:0 auto
    }
}
```

The expected result is

``` css
@media only screen and (min-width:1000px) {
    body {
        width:760px;
        margin:0 auto
    }
}
```

Note:
There is a space after **and**, if there is no space, some browser like chrome will not recognized  correctly.
