### ISSUE TITLE
New line added between each css declaration

### ISSUE THREAD

**Issue by tonyjessup** [beautify-web/js-beautify#523]
It seems prettify is adding extra lines to each css declaration in this particular file. Not sure how to fix this so it doesn't add extra lines.

Before:

``` CSS
html,
button,
input,
select,
textarea {
  color: #222;
}

body {
  font-size: 1em;
  line-height: 1.4;
}
```

After:
Selecting block and using Prettify Code with Node 0.10.31 in ST3 3065 running OSX 10.9.4

``` CSS
html, button, input, select, textarea {

    color: #222;

}

body {

    font-size: 1em;

    line-height: 1.4;

}
```

Prettify css settings:

``` JSON
    "css": {
        "allowed_file_extensions": ["css", "scss", "sass", "less"],
        "end_with_newline": false,
        "indent_char": " ",
        "indent_size": 4,
        "selector_separator": " ",
        "selector_separator_newline": false
    },
```
