### ISSUE TITLE
Extra newline is inserted after the comment line instead of before it

### ISSUE THREAD

**Issue by archersunx** [beautify-web/js-beautify#531]
Please have a check on below css codes,
**Original codes:**

``` css
/* Space out content a bit */
body {
  padding-top: 20px;
  padding-bottom: 20px;
}

/* Custom page header */
.header {
  border-bottom: 1px solid #e5e5e5;
}
```

**After formatted:**

``` css
/* Space out content a bit */

body {
    padding-top: 20px;
    padding-bottom: 20px;
}
/* Custom page header */

.header {
    border-bottom: 1px solid #e5e5e5;
}
```

Extra newline is inserted after the comment line instead of before it. I checked out the source code, it seems like a intentional behavior, but it sounds wired for me, as the comment is obviously for the next rule set, not the previous one.

**Comment by bor** [comment]
I've catched the same issue

**Comment by bitwiseman** [comment]
Too busy to work on this at this time.  Please help by submitting a PR with fix and tests.

**Comment by robsonrosa** [comment]
Same here. But adding a few more details, it  behaves differently depending on how you add your comment. 

`block comment` **outside** brackets adds an extra line before and after the comment each time you format.
`block comment` **inside** brackets works fine.
`inline comment` **outside** brackets works fine.
`inline comment` **inside** removes all spaces between comment and last character.

Example before formatting:

![image](https://cloud.githubusercontent.com/assets/2868031/26420810/31054692-409a-11e7-8e6d-040507b239a0.png)

Example after formatting:
![image](https://cloud.githubusercontent.com/assets/2868031/26420985/c22def5c-409a-11e7-9d81-58c4287e4274.png)

It's weird. If you use `inline comment` **outside** brackets and `block comment` **inside** brackets, everything works fine.

**Comment by NathanStrutz** [comment]
Please note that CSS does not have inline comments. Have we thought about the correct, most beautiful way to reformat this:

```css
/* block comment */
.selector {
  width: 0; /* inline comment */
}
```

It should either leave it alone, or it should move the inline comment above the line it comments on. I would never want to see the inline comment on its own line after the one it's marking up, which is what it does with the current release, afaik.
