### ISSUE TITLE
CSS: Preserve Newlines

### ISSUE THREAD

**Issue by parties** [beautify-web/js-beautify#537]
Maybe I'm not configuring it correctly, or maybe it's missing, but I have a great need for preserving my newlines in my css and can't seem to get it to work.

Here's my config:

```
"css": {
  "allowed_file_extensions": ["css", "scss", "sass", "less"],
  "end_with_newline": true,
  "indent_char": " ",
  "indent_size": 2,
  "selector_separator": " ",
  "selector_separator_newline": false,
  "preserve_newlines": true
}
```

**Comment by bor** [comment]
would be nice to have

**Comment by darlanalves** [comment]
+1² for SCSS files.

Issue #563 also has a similar problem. When I save/format a .scss file, the variables at the top and the import calls are all put together, making it hard to maintain. Would be super to just detect empty lines and keep them :+1: 

Just for reference:

```scss
@import "config";

$background: #ececec;
$color: #00aec8;

body {
	font-size: $font-size;
}
```

... goes like this:

```scss
@import "config";
$background: #ececec;
$color: #00aec8;
body {
	font-size: $font-size;
}
```
