### ISSUE TITLE
more Extra space after scss pseudo classes

### ISSUE THREAD

**Issue by darkraul79** [beautify-web/js-beautify#557]
Original 
```css
.pagination {
    width: 100%;
    clear: both;
    text-align: center;
	a:not(.peq) {
	    width: 50px;
	    margin: 1px;
	    &:hover {
	        font-weight: bold;
		}
	}
}
```

After Beauty 
```css
.pagination {
    width: 100%;
    clear: both;
    text-align: center;
    a: not(.peq) {
        width: 50px;
        margin: 1px;
        &:hover {
            font-weight: bold;
        }
    }
}
```
