### ISSUE TITLE
Equal Sign Removed from Filter Properties Alpha Opacity Assignment

### ISSUE THREAD

**Issue by mtpultz** [beautify-web/js-beautify#599]
Beautifying some CSS for the jQuery Colorbox plugin so I could customize it I noticed my Sass build starts to fail, and indicates that there is an issue on the line with a filter property where the assigned alpha property opacity values being set to 90 has the equal sign removed.

```CSS
// BEFORE LINTING
#cboxOverlay{background:url(images/overlay.png) repeat 0 0; opacity: 0.9; filter: alpha(opacity = 90);}
```

```CSS
// AFTER LINTING
#cboxOverlay {
    background: url(images/overlay.png) repeat 0 0;
    opacity: 0.9;
    filter: alpha(opacity 90);
}
```
