### ISSUE TITLE
Extra Space Added After Semi-Colon in IE Filter Property Value

### ISSUE THREAD

**Issue by mtpultz** [beautify-web/js-beautify#600]
Beautifying some CSS for the jQuery Colorbox plugin so I could customize it I noticed my Sass build starts to fail, and indicates that there is an issue on the line with an IE transform value where extra whitespace was added after the semi-colon after progid causing issues.

``` CSS
// BEFORE BEAUTIFY
.cboxIE #cboxTopLeft,
.cboxIE #cboxTopCenter,
.cboxIE #cboxTopRight,
.cboxIE #cboxBottomLeft,
.cboxIE #cboxBottomCenter,
.cboxIE #cboxBottomRight,
.cboxIE #cboxMiddleLeft,
.cboxIE #cboxMiddleRight {
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF, endColorstr=#00FFFFFF);
}
```

``` CSS
// AFTER BEAUTIFY
.cboxIE #cboxTopLeft,
.cboxIE #cboxTopCenter,
.cboxIE #cboxTopRight,
.cboxIE #cboxBottomLeft,
.cboxIE #cboxBottomCenter,
.cboxIE #cboxBottomRight,
.cboxIE #cboxMiddleLeft,
.cboxIE #cboxMiddleRight {
    filter: progid: DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF, endColorstr=#00FFFFFF);
}
```
