### ISSUE TITLE
newline_between_rules support for Sass (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [beautify-web/js-beautify#657]
Now `newline_between_rules` option in **v1.5.5** is supported for CSS only https://github.com/beautify-web/js-beautify/pull/574
So, in **Sass** for nesting doesn't work.

Here my `test.js` file:

``` js
var fs = require('fs');
var beautify_css = require('js-beautify').css;

fs.readFile('test.scss', 'utf8', function(err, data) {
  if (err) {
    throw err;
  }

  console.log(beautify_css(data, {
    indent_size: 2,
    newline_between_rules: true
  }));
});
```

Output:

``` sh
$ node test.js

.icons {
  padding: 0;
  li {
    display: inline-block;
  }
  a {
    display: block;
    color: #000;
  }
  a:hover {
    color: #ccc;
  }
}
```

I hope to add `newline_between_rules` support for **Sass**.
Regards.

**Comment by bitwiseman** [comment]
And what do you want it to look like?

**Comment by joseluisq** [comment]
Similar to CSS version https://github.com/beautify-web/js-beautify/pull/574
In general, one nesting level is enough.
Here an example:

```scss
// Icons
.icons {
  padding: 0;

  li {
    display: inline-block;
  }

  a {
    display: block;
    color: #000;
  }

  a:hover {
    color: #ccc;
  }
}

// Button
.button {
  &.primary {
    color: #4183c4;
  }

  &.primary:hover {
    color: lighten(#4183c4, 15%);
  }
}
```

**Comment by deepak8167** [comment]
Hi,
Is this work for scss rules. 


  .old_price {
    @include GibsonRegular();
    @include font-size(14);
    color: #646464;
    margin-left: 10px;
    text-decoration: line-through;

    .promovalue {
      @include GibsonRegular();
    }

  }

**Comment by echenley** [comment]
+1

**Comment by explorador** [comment]
+1

**Comment by chipcullen** [comment]
+1

**Comment by spacedawwwg** [comment]
+1

**Comment by spacedawwwg** [comment]
maybe an option like `newline_between_nested_rules: true` as it seems to be specifically an issue with nested?

`}` and `;` would need to consider the rule for nested new lines

**Comment by Billskate** [comment]
+1, also for less

**Comment by ms-carterk** [comment]
+1

**Comment by nevace** [comment]
+1

**Comment by Jakobud** [comment]
I can confirm that this is indeed a problem only with the nested rules. Current with `newline_between_rules: true` this:

```
body {
  background-color: #FFF;

  > div {
    background-color: #AAA;
  }
}

.container {
  color: blue;
}
```

Becomes this:

```
body {
  background-color: #FFF;
  > div {
    background-color: #AAA;
  }
}

.container {
  color: blue;
}
```

**Comment by danieloprado** [comment]
+1

**Comment by gligoran** [comment]
Any ETA on this thing?

**Comment by francislanglois** [comment]
+1

**Comment by pacochan** [comment]
+1

**Comment by jfily** [comment]
+1 :(

**Comment by Startcom** [comment]
+1

**Comment by zimmerboy** [comment]
Another +1

Sorry for the noise. I didn't know if another way to upvote this.

**Comment by gligoran** [comment]
@zimmerboy there's an "Add your reaction" button at the top right of every comment, which contains the +1 reaction (:+1:).

**Comment by sickboy** [comment]
My workaround in `css-beautify.js`:

1. Replace newLine function:
```
        print.newLine = function(keepWhitespace, keepNewLine) {
            if (output.length) {
                if (!keepWhitespace && output[output.length - 1] !== '\n') {
                    print.trim();
					if (keepNewLine) { output.push('\n'); }
                }

                output.push('\n');

                if (basebaseIndentString) {
                    output.push(basebaseIndentString);
                }
            }
        };
```

2. Change both `newline_between_rules` conditions and statements to:
```
                    if (newline_between_rules) {
                        print.newLine(false, true);
                    }
```

**Comment by bitwiseman** [comment]
@sickboy - Cool, start a pull request, add some tests. Please feel free to move this forward.

**Comment by mrahhal** [comment]
Is this coming anytime soon? It's my only blocker for using beautify for sass.

**Comment by bitwiseman** [comment]
@mrahhal - The issue is nearly two years old.  It seams @sickboy has done some work on this.  Someone just needs to make a pull request with tests.

Maybe you'd like to do this? See [CONTRIBUTING.md](https://github.com/beautify-web/js-beautify/blob/master/CONTRIBUTING.md).

**Comment by mrahhal** [comment]
@bitwiseman unfortunately I don't have the experience with this kind of projects nor the time. But my question is, so is everyone either using plain css or just sticking with how the current formatting works? That's weird for a very old but easy to solve issue .

@sickboy are you on this? Maybe I'll tackle it after all if nobody's active on this. Apart from some weird behavior with "max_preserve_newlines", this is really the only thing missing that's completely preventing me from using beautify.

**Comment by zimmerboy** [comment]
I wonder if pull request #1117 (**added preserve_newlines for css**) will help with this.

**Comment by mrahhal** [comment]
@zimmerboy yes that seems to be a fix for the current issue, but a different kind I think.

**Comment by jorgeramirez** [comment]
Is #1117 going to be merged? It seems to address this issue too.

**Comment by bitwiseman** [comment]
@jorgeramirez - Just waiting for fixes to previous feedback.

**Comment by jorgeramirez** [comment]
@bitwiseman great!

**Comment by royduin** [comment]
Any updates?

**Comment by bitwiseman** [comment]
@royduin - please test with the latest release.

**Comment by stgogm** [comment]
It seems to work fine but there's a little issue with comments. I know Bootstrap SCSS is not a great example, but still.

This is how the code is formatted on the repo:
![image](https://cloud.githubusercontent.com/assets/2774311/25088705/a632cc96-234e-11e7-8a41-aa1c2f4df0a0.png)

And this is after beautifying:
![image](https://cloud.githubusercontent.com/assets/2774311/25088720/bba116a0-234e-11e7-8e2f-0e38bde15a0a.png)

It works as expected but comments overlap with previous declaration, but if comments are formatted correctly, it works fine:
![image](https://cloud.githubusercontent.com/assets/2774311/25088750/f29d86ac-234e-11e7-8f15-427732dd530f.png)

Again, it's nothing really important, but Bootstrap is widely used :confused:

**Comment by bitwiseman** [comment]
@stgogm 
Please file a new issue. 
Also, please include text, not images.

**Comment by stgogm** [comment]
@bitwiseman Okay, sorry. Just wanted to note that as it's not really an issue if you respect the SCSS linter rules.

**Comment by bitwiseman** [comment]
@stgogm -  Cool, thanks for the info.  😄

**Comment by olets** [comment]
@stgogm while you have it set up, could you test the `newline_between_rules` issue? With

```javascript
newline_between_rules: true
```

does

```less
fieldset {
    border: 0;
    margin: 0;
    mind-width: 0;
    paddding: 0;
    &+fieldset {
        margin-top: $padding-large;
    }
}
```

become

```less
fieldset {
    border: 0;
    margin: 0;
    mind-width: 0;
    paddding: 0;

    &+fieldset {
        margin-top: $padding-large;
    }
}
```

**Comment by stgogm** [comment]
Actually, it makes no difference:

Code as authored (without new line in between):
```scss
form {
  display: block;
}

fieldset {
  border: 0;
  margin: 0;
  min-width: 0;
  padding: 0;
  & + fieldset {
    margin-top: $padding-large;
  }
}
```
After beautify with `"newline_between_rules": false`:

```scss
form {
  display: block;
}

fieldset {
  border: 0;
  margin: 0;
  min-width: 0;
  padding: 0;
  &+fieldset {
    margin-top: $padding-large;
  }
}
```
After beautify with `"newline_between_rules": true`:

```scss
form {
  display: block;
}

fieldset {
  border: 0;
  margin: 0;
  min-width: 0;
  padding: 0;
  &+fieldset {
    margin-top: $padding-large;
  }
}
```
It just removed the space between the `+`.
