### ISSUE TITLE
No new line after selector in scss files

### ISSUE THREAD

**Issue by piotros** [beautify-web/js-beautify#666]
There is a problem with "selector_separator_newline" option in scss files.
At the first level everything is ok. Problem occurs when we use nested selectors.
Instead of this:
```scss
.selector-1,
.selector-2 {
    .nested-selector-1, .nested-selector-2 {
        color: red;
    }
}
```
prettified output should look like this:
```scss
.selector-1,
.selector-2 {
    .nested-selector-1,
    .nested-selector-2 {
        color: red;
    }
}
```
