### ISSUE TITLE
selector_separator_newline dosen't work?

### ISSUE THREAD

**Issue by icewind7030** [beautify-web/js-beautify#705]
I use the HTML/CSS/JS prettify plugin  and change the prettify preference like below:

``` css
"css": {
    "allowed_file_extensions": ["css", "scss", "sass", "less"],
    "end_with_newline": false, // End output with newline
    "indent_char": " ", // Indentation character
    "indent_size": 4, // Indentation size
    "newline_between_rules": true, // Add a new line after every css rule
    "selector_separator": "",
    "selector_separator_newline": false // Separate selectors with newline or not (e.g. "a,\nbr" or "a, br")
  },
```

and  I expect the css code  

``` css
    fieldset,
    img,
    html,
    body,
    iframe {
        border: 0;
    }
```

 to be like 

``` css
    fieldset,img,html,body,iframe {
        border: 0;
    }
```

but the setting doesn't work, and everytime I manually change the css code like this:

``` css
    fieldset,img,html,body,iframe {
        border: 0;
    }
```

and press the ctrl+shift+h, the css code changes back to 

``` css
    fieldset,
    img,
    html,
    body,
    iframe {
        border: 0;
    }
```

Did I make any mistakes?
