### ISSUE TITLE
"wrap_attributes":"force" not working on Handlebars

### ISSUE THREAD

**Issue by jwhitmarsh** [beautify-web/js-beautify#795]

**Comment by bitwiseman** [comment]
Please provide repro steps and details.

**Comment by drewcovi** [comment]
Seeing this as well... using this in the Atom editor where html works a charm, but handlebars fails.

**Comment by drewcovi** [comment]
What details are needed? aside from creating a document and running the script?

**Comment by drewcovi** [comment]
```
  "atom-beautify":
    general:
      _analyticsUserId: "ccddff64-18a8-41db-a3b3-7d5ca10d9281"
    handlebars:
      indent_inner_html: true
      wrap_attributes: "force-aligned"
    html:
      indent_inner_html: true
      wrap_attributes: "force-aligned"
```

Pretty straight forward here,  no major tweaks. Comparing html and handlebars, handlebars pulls all attributes onto the same line.
