### ISSUE TITLE
Bug in Less mixins

### ISSUE THREAD

**Issue by baivong** [beautify-web/js-beautify#844]
I'm using package HTML-CSS-JS Prettify in Sublime Text 3.

Before:
```less
.mixin(@abc, @xyz) {
    @{abc}: @xyz;
}
```

After:
```less
.mixin(@abc, @xyz) {
    @ {
        abc
    }
    : @xyz;
}
```

**Comment by bitwiseman** [comment]
Cool thanks.

**Comment by agulado** [comment]
+1
less

Before：
```css
    .loop_section_top_ul_li(@i) when (@i>0) {
    	section.top ul li.l@{i} a{
        	background-position: ((@i)-1)*-100px -20px;
    	}
    	section.top ul li.l@{i} a.now{
        	background-position: ((@i)-1)*-100px 0;
    	}
    	.loop_section_top_ul_li((@i)-1);
    }
```

After：
```css
    .loop_section_top_ul_li(@i) when (@i>0) {
        section.top ul li.l@ {
            i
        }
        a {
            background-position: ((@i)-1)*-100px -20px;
        }
        section.top ul li.l@ {
            i
        }
        a.now {
            background-position: ((@i)-1)*-100px 0;
        }
        .loop_section_top_ul_li((@i)-1);
    }
```
