### ISSUE TITLE
Weird Beautify Style?

### ISSUE THREAD

**Issue by raulfunkie** [beautify-web/js-beautify#857]
it seems that beautify likes to add a double line before a comment, then a single line after a comment.
## Original

``` css
.box {
    border: 2px solid gray;
    padding: 10px;
    background: rgba(0, 0, 0, .5);
}

/* This is a CSS comment! */
.other-box {
    border: 1px solid red;
    padding: 4px;
    background: #fe4444;
}
```
## After beautify

``` css
.box {
    border: 2px solid gray;
    padding: 10px;
    background: rgba(0, 0, 0, .5);
}


/* This is a CSS comment! */

.other-box {
    border: 1px solid red;
    padding: 4px;
    background: #fe4444;
}
```
## Expected Outcome

Same as original
