### ISSUE TITLE
Media Queries style issue

### ISSUE THREAD

**Issue by raulfunkie** [beautify-web/js-beautify#863]
There seems to be another bug regarding media queries and how beautifier handles them.
## Original

``` css
@media only screen and (max-width: 40em) {
header {
    margin: 0 auto;
    padding: 10px;
    background: red;
    }

main {
    margin: 20px auto;
    padding: 4px;
    background: blue;
    }
}
```
## After Beautify

``` css
@media only screen and (max-width: 40em) {
header {
    margin: 0 auto;
    padding: 10px;
    background: red;
    }
main {
    margin: 20px auto;
    padding: 4px;
    background: blue;
    }
}
```
## Expected Outcome

Same as original

This is probably (and most likely) related to the issue #857 I reported a few days ago.
